### ISSUE TITLE
Initial repository setup

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-commenting#2]
This is an issue to track the initial repository setup:

- [x] Add official Jupyter copyright and license.
- [ ] Add standard sections to README, including team section.
- [x] Create skeleton for single npm package
- [ ] Create JLab style labels.

**Comment by saulshanabrook** [comment]
@karamba228 @hoo761 This is a good place to start for this repo, especially setting up a npm package for the JupyterLab extension.

**Comment by hoo761** [comment]
Here is the npm package skeleton. PR #6

**Comment by hoo761** [comment]
PR #7 
- Added more to the README including team sections
- Added JLab BSD 3-Clause License
